### ISSUE TITLE
Failed to compile Chinese

### ISSUE THREAD

**Issue by YanMing-lxb** [matjp/latex-preview#1]
```tex
\documentclass[12pt]{article}
\usepackage{ctex}

\title{Title}
\author{Your Name}
\date{\today}
\begin{document}

\maketitle
\section{First Section}
\Large
Hello World!\\
中文输入
\end{document}
```
This plugin is a very good thing, unfortunately it does not support Chinese. It is known that ctex macro package can support Chinese very well, ctex supports Chinese by lualatex-ja. Looking forward to your reply!

**Comment by matjp** [comment]
I tried your example and got the error "Package luatexja Error: DVI output is not supported in LuaTeX-ja."

DVI output is a fundamental requirement for LaTeX Previewer.

You could either raise a request with the luatexja maintainers to add DVI support or find another package that does support DVI output.
