### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by YaoXiufeng** [matjp/latex-preview#5]
dvilualatex --halt-on-error --interaction=nonstopmode --synctex=-1 c:\Users\yaoxi\Desktop\Study\Note\Going down functors\GoingDownFunctors.tex
This is LuaTeX, Version 1.18.1 (MiKTeX 24.4)
 restricted system commands enabled.
! I can't find file `c:/Users/yaoxi/Desktop/Study/Note/Going'.
<*> c:/Users/yaoxi/Desktop/Study/Note/Going 
                                         down functors\GoingDownFunctors.tex
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<*> c:/Users/yaoxi/Desktop/Study/Note/Going 
                                         down functors\GoingDownFunctors.tex
 270 words of node memory still in use:
   1 hlist, 39 glue_spec nodes
   avail lists: 2:12,3:3,4:1,5:1
!  ==> Fatal error occurred, bad output DVI file produced!
No pages of output.
Transcript written on texput.log.

Error: Command failed: dvilualatex --halt-on-error --interaction=nonstopmode --synctex=-1 c:\Users\yaoxi\Desktop\Study\Note\Going down functors\GoingDownFunctors.tex

Could not generate dvi file - review the log for errors.

**Comment by matjp** [comment]
I think this is because of spaces in your file path. Try renaming the directory 'Going down functors' to remove the spaces.

**Comment by YaoXiufeng** [comment]
Thank you very much for your support and reply, but now there is a new problem:
! I can't find file `extension-output-mjpvs.latex-previewer-#1-LaTeX'.
<*> extension-output-mjpvs.latex-previewer-#1-LaTeX 
                                                 Preview
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<*> extension-output-mjpvs.latex-previewer-#1-LaTeX 
                                                 Preview
 270 words of node memory still in use:
   1 hlist, 39 glue_spec nodes
   avail lists: 2:12,3:3,4:1,5:1
!  ==> Fatal error occurred, bad output DVI file produced!
No pages of output.
Transcript written on texput.log.

Error: Command failed: dvilualatex --halt-on-error --interaction=nonstopmode --synctex=-1 extension-output-mjpvs.latex-previewer-#1-LaTeX Preview

Could not generate dvi file - review the log for errors.

**Comment by YaoXiufeng** [comment]
i make a test file, and there is one line :\documentclass[12pt]{article}

the log for errors is as following:

This is LuaTeX, Version 1.18.1 (MiKTeX 24.4) (format=dvilualatex 2024.6.11)  16 JUN 2024 19:25
 restricted system commands enabled.
**c:/Users/yaoxi/Desktop/Study/Note/test/test.tex
(c:/Users/yaoxi/Desktop/Study/Note/test/test.tex
LaTeX2e <2024-06-01>
L3 programming layer <2024-05-08>
Lua module: luaotfload 2024-02-14 3.28 Lua based OpenType font support
Lua module: lualibs 2023-07-13 2.76 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2023-07-13 2.76 ConTeXt Lua libraries -- extended c
ollection.
luaotfload | conf : Root cache directory is "C:/Users/yaoxi/AppData/Local/MiKTeX
/luatex-cache/generic/names".
luaotfload | init : Loading fontloader "fontloader-2023-12-28.lua" from kpse-res
olved path "C:/Users/yaoxi/AppData/Local/Programs/MiKTeX/tex/luatex/luaotfload/f
ontloader-2023-12-28.lua".
Lua-only attribute luaotfload@noligature = 1
luaotfload | init : Context OpenType loader version 3.134
Inserting `luaotfload.node_processor' in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' in `hpack_filter'.
Inserting `luaotfload.glyph_stream' in `glyph_stream_provider'.
Inserting `luaotfload.define_font' in `define_font'.
Lua-only attribute luaotfload_color_attribute = 2
luaotfload | conf : Root cache directory is "C:/Users/yaoxi/AppData/Local/MiKTeX
/luatex-cache/generic/names".
Lua-only attribute luaotfload.letterspace_done = 3
Inserting `luaotfload.aux.set_sscale_dimens' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_font_index' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.patch_cambria_domh' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.fixup_fontdata' in `luaotfload.patch_font_unsafe'.
Inserting `luaotfload.aux.set_capheight' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_xheight' in `luaotfload.patch_font'.
Inserting `luaotfload.rewrite_fontname' in `luaotfload.patch_font'.
Inserting `tracingstacklevels' in `input_level_string'.)
! Emergency stop.
<*> c:/Users/yaoxi/Desktop/Study/Note/test/test.tex
                                                

Here is how much of LuaTeX's memory you used:
 18 strings out of 475944
 100000,1977958 words of node,token memory allocated
 301 words of node memory still in use:
   1 hlist, 1 dir, 3 kern, 1 glyph, 1 attribute, 39 glue_spec, 1 attribute_list 
nodes
   avail lists: 2:10,3:3,4:1
 22729 multiletter control sequences out of 65536+600000
 14 fonts using 591679 bytes
 12i,0n,13p,78b,15s stack positions out of 10000i,1000n,20000p,200000b,200000s
!  ==> Fatal error occurred, bad output DVI file produced!
No pages of output.

**Comment by matjp** [comment]
That is not a valid TeX file. Try this as a minimal example:

\documentclass[12pt]{article}

\begin{document}

\begin{center}
{Minimal example}
\end{center}

\end{document}
