### ISSUE TITLE
Quote the latex file name to support spaces in the path

### ISSUE THREAD

**Issue by timlg07** [matjp/latex-preview#6]
https://github.com/matjp/latex-preview/blob/184a91173867db3a0dd5622fad24a08b36d586d2/src/DocumentPanel.ts#L251

**Comment by matjp** [comment]
Any solution to this problem has to be workable for both Linux and Windows systems. Since Linux allows the quote character to be used in filenames, this solution could fail on valid filenames.

**Comment by timlg07** [comment]
What about checking if `this.editor.document.fileName` contains any quotes and only adding the quotes in this case? As quotes are uncommon in filenames, this would solve the issue in most cases without changing the behavior in case of quotes.
